// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SisControl.Server.Data;

#nullable disable

namespace SisControl.Server.Migrations
{
    [DbContext(typeof(DataContexto))]
    partial class DataContextoModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SisControl.Client.Services.Dtos.LancamentoParaFiltrarDto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Ano")
                        .HasColumnType("int");

                    b.Property<string>("Comunidade")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ComunidadeId")
                        .HasColumnType("int");

                    b.Property<int?>("LancamentoParaFiltrarDtoId")
                        .HasColumnType("int");

                    b.Property<string>("Pessoa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PessoaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LancamentoParaFiltrarDtoId");

                    b.ToTable("LancamentoParaFiltrarDtos");
                });

            modelBuilder.Entity("SisControl.Client.Services.Dtos.LancamentosConsultaDto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Ano")
                        .HasColumnType("int");

                    b.Property<string>("Comunidade")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ComunidadeId")
                        .HasColumnType("int");

                    b.Property<int?>("LancamentosConsultaDtoId")
                        .HasColumnType("int");

                    b.Property<bool>("MAbr")
                        .HasColumnType("bit");

                    b.Property<bool>("MAgo")
                        .HasColumnType("bit");

                    b.Property<bool>("MDez")
                        .HasColumnType("bit");

                    b.Property<bool>("MFev")
                        .HasColumnType("bit");

                    b.Property<bool>("MJan")
                        .HasColumnType("bit");

                    b.Property<bool>("MJul")
                        .HasColumnType("bit");

                    b.Property<bool>("MJun")
                        .HasColumnType("bit");

                    b.Property<bool>("MMai")
                        .HasColumnType("bit");

                    b.Property<bool>("MMar")
                        .HasColumnType("bit");

                    b.Property<bool>("MNov")
                        .HasColumnType("bit");

                    b.Property<bool>("MOut")
                        .HasColumnType("bit");

                    b.Property<bool>("MSet")
                        .HasColumnType("bit");

                    b.Property<string>("Pessoa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PessoaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LancamentosConsultaDtoId");

                    b.ToTable("LancamentoDtos");
                });

            modelBuilder.Entity("SisControl.Shared.Models.EntidadeComunidade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Bairro")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CEP")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cnpj")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Complemento")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DataFundacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Endereco")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Fone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UF")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("EntidadeComunidades");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Bairro = "Ipiranga",
                            CEP = "29202-515",
                            Cidade = "Guarapari",
                            Cnpj = "27.054.162/009620",
                            Complemento = "Com. Divino",
                            DataFundacao = new DateTime(2016, 8, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "ofirdev@outlook.com",
                            Endereco = "R. Eliziário Lourenço Dias, 505",
                            Fone = "(27) 99937-1549",
                            Nome = "Divino Espírito Santo",
                            UF = "ES"
                        },
                        new
                        {
                            Id = 2,
                            Bairro = "São João",
                            CEP = "29202-515",
                            Cidade = "Guarapari",
                            Cnpj = "27.054.162/009620",
                            Complemento = "Com. N. S. do Carmo",
                            DataFundacao = new DateTime(2016, 8, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "ofirdev@outlook.com",
                            Endereco = "R. Eliziário Lourenço Dias, 505",
                            Fone = "(27) 99937-1549",
                            Nome = "Nossa Senhora do Carmo",
                            UF = "ES"
                        },
                        new
                        {
                            Id = 3,
                            Bairro = "Ipiranga",
                            CEP = "29202-515",
                            Cidade = "Guarapari",
                            Cnpj = "27.054.162/009620",
                            Complemento = "Com. Rainha da Paz",
                            DataFundacao = new DateTime(2016, 8, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "ofirdev@outlook.com",
                            Endereco = "R. Eliziário Lourenço Dias, 505",
                            Fone = "(27) 99937-1549",
                            Nome = "Nossa Senhora Rainha da Paz",
                            UF = "ES"
                        },
                        new
                        {
                            Id = 4,
                            Bairro = "Praia do Riacho",
                            CEP = "29202-515",
                            Cidade = "Guarapari",
                            Cnpj = "27.054.162/009620",
                            Complemento = "Com. Sagrada Família",
                            DataFundacao = new DateTime(2016, 8, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "ofirdev@outlook.com",
                            Endereco = "R. Eliziário Lourenço Dias, 505",
                            Fone = "(27) 99937-1549",
                            Nome = "Sagrada Família",
                            UF = "ES"
                        },
                        new
                        {
                            Id = 5,
                            Bairro = "Kubitscheck",
                            CEP = "29202-515",
                            Cidade = "Guarapari",
                            Cnpj = "27.054.162/009620",
                            Complemento = "Com. Santa Cruz",
                            DataFundacao = new DateTime(2016, 8, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "ofirdev@outlook.com",
                            Endereco = "R. Eliziário Lourenço Dias, 505",
                            Fone = "(27) 99937-1549",
                            Nome = "Santa Cruz",
                            UF = "ES"
                        },
                        new
                        {
                            Id = 6,
                            Bairro = "Santa Margarida",
                            CEP = "29202-515",
                            Cidade = "Guarapari",
                            Cnpj = "27.054.162/009620",
                            Complemento = "Com. Santa Margarida",
                            DataFundacao = new DateTime(2016, 8, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "ofirdev@outlook.com",
                            Endereco = "R. Eliziário Lourenço Dias, 505",
                            Fone = "(27) 99937-1549",
                            Nome = "Santa Margarida",
                            UF = "ES"
                        },
                        new
                        {
                            Id = 7,
                            Bairro = "Concha D'Ostra",
                            CEP = "29202-515",
                            Cidade = "Guarapari",
                            Cnpj = "27.054.162/009620",
                            Complemento = "Com. Santo Expedito",
                            DataFundacao = new DateTime(2016, 8, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "ofirdev@outlook.com",
                            Endereco = "R. Eliziário Lourenço Dias, 505",
                            Fone = "(27) 99937-1549",
                            Nome = "Santo Expedito",
                            UF = "ES"
                        },
                        new
                        {
                            Id = 8,
                            Bairro = "Prainha de Olaria",
                            CEP = "29202-515",
                            Cidade = "Guarapari",
                            Cnpj = "27.054.162/009620",
                            Complemento = "Com. São João",
                            DataFundacao = new DateTime(2016, 8, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "ofirdev@outlook.com",
                            Endereco = "R. Eliziário Lourenço Dias, 505",
                            Fone = "(27) 99937-1549",
                            Nome = "São João Batista",
                            UF = "ES"
                        },
                        new
                        {
                            Id = 9,
                            Bairro = "Olaria",
                            CEP = "29202-515",
                            Cidade = "Guarapari",
                            Cnpj = "27.054.162/009620",
                            Complemento = "Com. São Judas",
                            DataFundacao = new DateTime(2016, 8, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "ofirdev@outlook.com",
                            Endereco = "R. Eliziário Lourenço Dias, 505",
                            Fone = "(27) 99937-1549",
                            Nome = "São Judas Tadeu",
                            UF = "ES"
                        },
                        new
                        {
                            Id = 10,
                            Bairro = "Coroado",
                            CEP = "29202-515",
                            Cidade = "Guarapari",
                            Cnpj = "27.054.162/009620",
                            Complemento = "Com. São Sebastião",
                            DataFundacao = new DateTime(2016, 8, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "ofirdev@outlook.com",
                            Endereco = "R. Eliziário Lourenço Dias, 505",
                            Fone = "(27) 99937-1549",
                            Nome = "São Sebastião",
                            UF = "ES"
                        });
                });

            modelBuilder.Entity("SisControl.Shared.Models.EntidadeLancamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Ano")
                        .HasColumnType("int");

                    b.Property<int?>("ComunidadeId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<bool>("MAbr")
                        .HasColumnType("bit");

                    b.Property<bool>("MAgo")
                        .HasColumnType("bit");

                    b.Property<bool>("MDez")
                        .HasColumnType("bit");

                    b.Property<bool>("MFev")
                        .HasColumnType("bit");

                    b.Property<bool>("MJan")
                        .HasColumnType("bit");

                    b.Property<bool>("MJul")
                        .HasColumnType("bit");

                    b.Property<bool>("MJun")
                        .HasColumnType("bit");

                    b.Property<bool>("MMai")
                        .HasColumnType("bit");

                    b.Property<bool>("MMar")
                        .HasColumnType("bit");

                    b.Property<bool>("MNov")
                        .HasColumnType("bit");

                    b.Property<bool>("MOut")
                        .HasColumnType("bit");

                    b.Property<bool>("MSet")
                        .HasColumnType("bit");

                    b.Property<int?>("PessoaId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("EntidadeLancamentos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ano = 2023,
                            ComunidadeId = 1,
                            MAbr = false,
                            MAgo = false,
                            MDez = true,
                            MFev = true,
                            MJan = true,
                            MJul = false,
                            MJun = false,
                            MMai = true,
                            MMar = true,
                            MNov = false,
                            MOut = false,
                            MSet = true,
                            PessoaId = 1
                        },
                        new
                        {
                            Id = 2,
                            Ano = 2023,
                            ComunidadeId = 3,
                            MAbr = true,
                            MAgo = false,
                            MDez = false,
                            MFev = true,
                            MJan = false,
                            MJul = false,
                            MJun = false,
                            MMai = true,
                            MMar = true,
                            MNov = true,
                            MOut = false,
                            MSet = true,
                            PessoaId = 2
                        },
                        new
                        {
                            Id = 3,
                            Ano = 2023,
                            ComunidadeId = 8,
                            MAbr = true,
                            MAgo = false,
                            MDez = false,
                            MFev = false,
                            MJan = true,
                            MJul = false,
                            MJun = false,
                            MMai = true,
                            MMar = true,
                            MNov = true,
                            MOut = true,
                            MSet = true,
                            PessoaId = 3
                        },
                        new
                        {
                            Id = 4,
                            Ano = 2023,
                            ComunidadeId = 1,
                            MAbr = true,
                            MAgo = false,
                            MDez = false,
                            MFev = true,
                            MJan = true,
                            MJul = false,
                            MJun = false,
                            MMai = true,
                            MMar = false,
                            MNov = false,
                            MOut = false,
                            MSet = true,
                            PessoaId = 2
                        },
                        new
                        {
                            Id = 5,
                            Ano = 2023,
                            ComunidadeId = 9,
                            MAbr = true,
                            MAgo = false,
                            MDez = false,
                            MFev = true,
                            MJan = true,
                            MJul = false,
                            MJun = false,
                            MMai = true,
                            MMar = true,
                            MNov = false,
                            MOut = false,
                            MSet = false,
                            PessoaId = 1
                        },
                        new
                        {
                            Id = 6,
                            Ano = 2022,
                            ComunidadeId = 1,
                            MAbr = false,
                            MAgo = false,
                            MDez = true,
                            MFev = true,
                            MJan = true,
                            MJul = false,
                            MJun = false,
                            MMai = true,
                            MMar = true,
                            MNov = false,
                            MOut = false,
                            MSet = true,
                            PessoaId = 1
                        },
                        new
                        {
                            Id = 7,
                            Ano = 2021,
                            ComunidadeId = 3,
                            MAbr = true,
                            MAgo = false,
                            MDez = false,
                            MFev = true,
                            MJan = false,
                            MJul = false,
                            MJun = false,
                            MMai = true,
                            MMar = true,
                            MNov = true,
                            MOut = false,
                            MSet = true,
                            PessoaId = 2
                        },
                        new
                        {
                            Id = 8,
                            Ano = 2021,
                            ComunidadeId = 8,
                            MAbr = true,
                            MAgo = false,
                            MDez = false,
                            MFev = false,
                            MJan = true,
                            MJul = false,
                            MJun = false,
                            MMai = true,
                            MMar = true,
                            MNov = true,
                            MOut = true,
                            MSet = true,
                            PessoaId = 3
                        },
                        new
                        {
                            Id = 9,
                            Ano = 2022,
                            ComunidadeId = 1,
                            MAbr = true,
                            MAgo = false,
                            MDez = false,
                            MFev = true,
                            MJan = true,
                            MJul = false,
                            MJun = false,
                            MMai = true,
                            MMar = false,
                            MNov = false,
                            MOut = false,
                            MSet = true,
                            PessoaId = 2
                        },
                        new
                        {
                            Id = 10,
                            Ano = 2022,
                            ComunidadeId = 6,
                            MAbr = true,
                            MAgo = false,
                            MDez = false,
                            MFev = true,
                            MJan = true,
                            MJul = false,
                            MJun = false,
                            MMai = true,
                            MMar = true,
                            MNov = false,
                            MOut = false,
                            MSet = false,
                            PessoaId = 1
                        },
                        new
                        {
                            Id = 11,
                            Ano = 2023,
                            ComunidadeId = 1,
                            MAbr = false,
                            MAgo = false,
                            MDez = true,
                            MFev = true,
                            MJan = true,
                            MJul = false,
                            MJun = false,
                            MMai = true,
                            MMar = true,
                            MNov = false,
                            MOut = false,
                            MSet = true,
                            PessoaId = 1
                        },
                        new
                        {
                            Id = 12,
                            Ano = 2023,
                            ComunidadeId = 3,
                            MAbr = true,
                            MAgo = false,
                            MDez = false,
                            MFev = true,
                            MJan = false,
                            MJul = false,
                            MJun = false,
                            MMai = true,
                            MMar = true,
                            MNov = true,
                            MOut = false,
                            MSet = true,
                            PessoaId = 2
                        },
                        new
                        {
                            Id = 13,
                            Ano = 2023,
                            ComunidadeId = 8,
                            MAbr = true,
                            MAgo = false,
                            MDez = false,
                            MFev = false,
                            MJan = true,
                            MJul = false,
                            MJun = false,
                            MMai = true,
                            MMar = true,
                            MNov = true,
                            MOut = true,
                            MSet = true,
                            PessoaId = 3
                        },
                        new
                        {
                            Id = 14,
                            Ano = 2023,
                            ComunidadeId = 1,
                            MAbr = true,
                            MAgo = false,
                            MDez = false,
                            MFev = true,
                            MJan = true,
                            MJul = false,
                            MJun = false,
                            MMai = true,
                            MMar = false,
                            MNov = false,
                            MOut = false,
                            MSet = true,
                            PessoaId = 2
                        },
                        new
                        {
                            Id = 15,
                            Ano = 2023,
                            ComunidadeId = 9,
                            MAbr = true,
                            MAgo = false,
                            MDez = false,
                            MFev = true,
                            MJan = true,
                            MJul = false,
                            MJun = false,
                            MMai = true,
                            MMar = true,
                            MNov = false,
                            MOut = false,
                            MSet = false,
                            PessoaId = 1
                        },
                        new
                        {
                            Id = 16,
                            Ano = 2022,
                            ComunidadeId = 1,
                            MAbr = false,
                            MAgo = false,
                            MDez = true,
                            MFev = true,
                            MJan = true,
                            MJul = false,
                            MJun = false,
                            MMai = true,
                            MMar = true,
                            MNov = false,
                            MOut = false,
                            MSet = true,
                            PessoaId = 1
                        },
                        new
                        {
                            Id = 17,
                            Ano = 2021,
                            ComunidadeId = 3,
                            MAbr = true,
                            MAgo = false,
                            MDez = false,
                            MFev = true,
                            MJan = false,
                            MJul = false,
                            MJun = false,
                            MMai = true,
                            MMar = true,
                            MNov = true,
                            MOut = false,
                            MSet = true,
                            PessoaId = 2
                        },
                        new
                        {
                            Id = 18,
                            Ano = 2021,
                            ComunidadeId = 8,
                            MAbr = true,
                            MAgo = false,
                            MDez = false,
                            MFev = false,
                            MJan = true,
                            MJul = false,
                            MJun = false,
                            MMai = true,
                            MMar = true,
                            MNov = true,
                            MOut = true,
                            MSet = true,
                            PessoaId = 3
                        },
                        new
                        {
                            Id = 19,
                            Ano = 2022,
                            ComunidadeId = 1,
                            MAbr = true,
                            MAgo = false,
                            MDez = false,
                            MFev = true,
                            MJan = true,
                            MJul = false,
                            MJun = false,
                            MMai = true,
                            MMar = false,
                            MNov = false,
                            MOut = false,
                            MSet = true,
                            PessoaId = 2
                        },
                        new
                        {
                            Id = 20,
                            Ano = 2022,
                            ComunidadeId = 6,
                            MAbr = true,
                            MAgo = false,
                            MDez = false,
                            MFev = true,
                            MJan = true,
                            MJul = false,
                            MJun = false,
                            MMai = true,
                            MMar = true,
                            MNov = false,
                            MOut = false,
                            MSet = false,
                            PessoaId = 1
                        });
                });

            modelBuilder.Entity("SisControl.Shared.Models.EntidadePessoa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Bairro")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CEP")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Complemento")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DataAtualizacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Endereco")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Fone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UF")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("EntidadePessoas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Bairro = "Este Aqui",
                            CEP = "29.200-001",
                            Cidade = "Guarapari",
                            Complemento = "Apto 001",
                            Cpf = "111.111.111-11",
                            DataAtualizacao = new DateTime(2023, 8, 7, 22, 19, 6, 394, DateTimeKind.Local).AddTicks(7495),
                            DataCadastro = new DateTime(2023, 8, 7, 22, 19, 6, 394, DateTimeKind.Local).AddTicks(7485),
                            DataNascimento = new DateTime(1972, 12, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "testeum@teste.com",
                            Endereco = "Rua da minha casa, 001",
                            Fone = "(27) 99999-1234",
                            Nome = "Primeira Pessoa Cadastrada",
                            UF = "ES"
                        },
                        new
                        {
                            Id = 2,
                            Bairro = "Este Aqui",
                            CEP = "29.200-002",
                            Cidade = "Guarapari",
                            Complemento = "Apto 002",
                            Cpf = "222.222.222-22",
                            DataAtualizacao = new DateTime(2023, 8, 7, 22, 19, 6, 394, DateTimeKind.Local).AddTicks(7580),
                            DataCadastro = new DateTime(2023, 8, 7, 22, 19, 6, 394, DateTimeKind.Local).AddTicks(7580),
                            DataNascimento = new DateTime(1974, 7, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "testedois@teste.com",
                            Endereco = "Rua da minha casa, 002",
                            Fone = "(27) 99999-2345",
                            Nome = "Segunda Pessoa Cadastrada",
                            UF = "ES"
                        },
                        new
                        {
                            Id = 3,
                            Bairro = "Este Aqui",
                            CEP = "29.200-002",
                            Cidade = "Guarapari",
                            Complemento = "Apto 002",
                            Cpf = "222.222.222-22",
                            DataAtualizacao = new DateTime(2023, 8, 7, 22, 19, 6, 394, DateTimeKind.Local).AddTicks(7591),
                            DataCadastro = new DateTime(2023, 8, 7, 22, 19, 6, 394, DateTimeKind.Local).AddTicks(7591),
                            DataNascimento = new DateTime(1974, 7, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "testedois@teste.com",
                            Endereco = "Rua da minha casa, 002",
                            Fone = "(27) 99999-2345",
                            Nome = "Terceira Pessoa Cadastrada",
                            UF = "ES"
                        },
                        new
                        {
                            Id = 4,
                            Bairro = "Este Aqui",
                            CEP = "29.200-002",
                            Cidade = "Guarapari",
                            Complemento = "Apto 002",
                            Cpf = "222.222.222-22",
                            DataAtualizacao = new DateTime(2023, 8, 7, 22, 19, 6, 394, DateTimeKind.Local).AddTicks(7596),
                            DataCadastro = new DateTime(2023, 8, 7, 22, 19, 6, 394, DateTimeKind.Local).AddTicks(7596),
                            DataNascimento = new DateTime(1974, 7, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "testedois@teste.com",
                            Endereco = "Rua da minha casa, 002",
                            Fone = "(27) 99999-2345",
                            Nome = "Quarta Pessoa Cadastrada",
                            UF = "ES"
                        },
                        new
                        {
                            Id = 5,
                            Bairro = "Este Aqui",
                            CEP = "29.200-002",
                            Cidade = "Guarapari",
                            Complemento = "Apto 002",
                            Cpf = "222.222.222-22",
                            DataAtualizacao = new DateTime(2023, 8, 7, 22, 19, 6, 394, DateTimeKind.Local).AddTicks(7602),
                            DataCadastro = new DateTime(2023, 8, 7, 22, 19, 6, 394, DateTimeKind.Local).AddTicks(7601),
                            DataNascimento = new DateTime(1974, 7, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "testedois@teste.com",
                            Endereco = "Rua da minha casa, 002",
                            Fone = "(27) 99999-2345",
                            Nome = "Quinta Pessoa Cadastrada",
                            UF = "ES"
                        },
                        new
                        {
                            Id = 6,
                            Bairro = "Este Aqui",
                            CEP = "29.200-002",
                            Cidade = "Guarapari",
                            Complemento = "Apto 002",
                            Cpf = "222.222.222-22",
                            DataAtualizacao = new DateTime(2023, 8, 7, 22, 19, 6, 394, DateTimeKind.Local).AddTicks(7607),
                            DataCadastro = new DateTime(2023, 8, 7, 22, 19, 6, 394, DateTimeKind.Local).AddTicks(7606),
                            DataNascimento = new DateTime(1974, 7, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "testedois@teste.com",
                            Endereco = "Rua da minha casa, 002",
                            Fone = "(27) 99999-2345",
                            Nome = "Sexta Pessoa Cadastrada",
                            UF = "ES"
                        },
                        new
                        {
                            Id = 7,
                            Bairro = "Este Aqui",
                            CEP = "29.200-003",
                            Cidade = "Guarapari",
                            Complemento = "Apto 003",
                            Cpf = "333.333.333-33",
                            DataAtualizacao = new DateTime(2023, 8, 7, 22, 19, 6, 394, DateTimeKind.Local).AddTicks(7612),
                            DataCadastro = new DateTime(2023, 8, 7, 22, 19, 6, 394, DateTimeKind.Local).AddTicks(7612),
                            DataNascimento = new DateTime(1997, 9, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "testetres@teste.com",
                            Endereco = "Rua da minha casa, 003",
                            Fone = "(27) 99999-3456",
                            Nome = "Setima Pessoa Cadastrada",
                            UF = "ES"
                        });
                });

            modelBuilder.Entity("SisControl.Shared.Models.EntidadeUsuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ComunidadeId")
                        .HasColumnType("int");

                    b.Property<int>("Nivel")
                        .HasColumnType("int");

                    b.Property<int>("PessoaId")
                        .HasColumnType("int");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("EntidadeUsuarios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ComunidadeId = 1,
                            Nivel = 0,
                            PessoaId = 1,
                            Senha = "sem"
                        },
                        new
                        {
                            Id = 2,
                            ComunidadeId = 2,
                            Nivel = 0,
                            PessoaId = 2,
                            Senha = "sem"
                        },
                        new
                        {
                            Id = 3,
                            ComunidadeId = 3,
                            Nivel = 0,
                            PessoaId = 1,
                            Senha = "sem"
                        },
                        new
                        {
                            Id = 4,
                            ComunidadeId = 5,
                            Nivel = 0,
                            PessoaId = 1,
                            Senha = "sem"
                        },
                        new
                        {
                            Id = 5,
                            ComunidadeId = 8,
                            Nivel = 0,
                            PessoaId = 3,
                            Senha = "sem"
                        });
                });

            modelBuilder.Entity("SisControl.Client.Services.Dtos.LancamentoParaFiltrarDto", b =>
                {
                    b.HasOne("SisControl.Client.Services.Dtos.LancamentoParaFiltrarDto", null)
                        .WithMany("LancamentoParaFiltrarDtos")
                        .HasForeignKey("LancamentoParaFiltrarDtoId");
                });

            modelBuilder.Entity("SisControl.Client.Services.Dtos.LancamentosConsultaDto", b =>
                {
                    b.HasOne("SisControl.Client.Services.Dtos.LancamentosConsultaDto", null)
                        .WithMany("LancamentoDtos")
                        .HasForeignKey("LancamentosConsultaDtoId");
                });

            modelBuilder.Entity("SisControl.Client.Services.Dtos.LancamentoParaFiltrarDto", b =>
                {
                    b.Navigation("LancamentoParaFiltrarDtos");
                });

            modelBuilder.Entity("SisControl.Client.Services.Dtos.LancamentosConsultaDto", b =>
                {
                    b.Navigation("LancamentoDtos");
                });
#pragma warning restore 612, 618
        }
    }
}
